src/getZodiosEndpointDescriptionFromOpenApiDoc.ts
tests/missing-operationId-variables-undefined_Body.test.ts
tests/ref-in-another-file.test.ts

fix https://github.com/astahmer/openapi-zod-client/issues/15

fix(#15): handle missing operationId for requestBody var name

---

README.md
src/__snapshots__/samples.test.ts.snap
src/generateZodClientFromOpenAPI.test.ts
src/getZodiosEndpointDefinitionFromOpenApiDoc.test.ts
src/getZodiosEndpointDefinitionFromOpenApiDoc.ts
src/openApiToZod.ts
tests/validations.test.ts

https://github.com/astahmer/openapi-zod-client/issues/8
https://github.com/astahmer/openapi-zod-client/issues/9

feat: string/number/array validations + format #8 + #9

---

src/generateZodClientFromOpenAPI.test.ts
src/getZodiosEndpointDefinitionList.test.ts
src/getZodiosEndpointDefinitionList.ts
src/openApiToZod.ts
tests/__snapshots__/samples.test.ts.snap
tests/same-schema-different-name.test.ts

closes https://github.com/astahmer/openapi-zod-client/issues/7

feat: adds z.default(xxx)

---

lib/src/openApiToZod.ts
lib/tests/missing-zod-chains-on-z-object-with-refs-props.test.ts

https://github.com/astahmer/openapi-zod-client/issues/49#issuecomment-1346512748

fix: missing zod chains on z.object(..) refs props

---

lib/package.json
lib/src/openApiToTypescript.ts
lib/src/openApiToZod.ts
lib/src/schema-complexity.ts
lib/tests/schema-type-list-3.1.test.ts
pnpm-lock.yaml

https://github.com/astahmer/openapi-zod-client/issues/60
https://spec.openapis.org/oas/v3.1.0#schema-object
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-7.6.1

feat(#60): support schema.type list from openapi 3.1

---

examples/petstore-minimal.json
examples/repro.yaml
lib/src/openApiToTypescript.ts
lib/src/openApiToZod.test.ts
lib/src/openApiToZod.ts
lib/src/schema-complexity.ts
lib/tests/schema-type-list-3.1.test.ts
playground/src/Playground/Playground.machine.ts
playground/src/Playground/PlaygroundWithMachine.tsx
playground/src/Playground/presets.ts

https://github.com/astahmer/openapi-zod-client/issues/67

fix(#67): treat `null` with higher priority

---

.changeset/selfish-kids-compare.md
.changeset/tough-steaks-bake.md
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/getHandlebars.ts
lib/src/templates/default.hbs
lib/src/templates/grouped.hbs
lib/tests/allOf-missing-and.test.ts
lib/tests/enum-min-max.test.ts
lib/tests/errors-responses.test.ts
lib/tests/export-schemas-option.test.ts
lib/tests/group-strategy.test.ts
lib/tests/handle-props-with-special-characters.test.ts
lib/tests/handle-refs-with-dots-in-name.test.ts
lib/tests/inline-simple-schemas.test.ts
lib/tests/is-main-response.test.ts
lib/tests/main-description-as-fallback.test.ts
lib/tests/min-with-max.test.ts
lib/tests/missing-zod-chains-on-z-object-with-refs-props.test.ts
lib/tests/name-starting-with-number.test.ts
lib/tests/name-with-special-characters.test.ts
lib/tests/number-default-as-number.test.ts
lib/tests/numerical-enum.test.ts
lib/tests/param-with-content.test.ts
lib/tests/recursive-schema.test.ts
lib/tests/same-schema-different-name.test.ts
lib/tests/samples.test.ts
lib/tests/schema-name-already-used.test.ts
lib/tests/schema-type-list-3.1.test.ts
lib/tests/schema-type-wrong-case.test.ts

https://github.com/astahmer/openapi-zod-client/issues/63#issuecomment-1384263939

feat(templates): export createApiClient fn + schemas object

---

.changeset/stupid-bugs-visit.md
README.md
examples/basic/package.json
examples/basic/petstore-client.ts
examples/schemas-only/petstore-schemas.ts
lib/README.md
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/getZodiosEndpointDefinitionList.test.ts
lib/src/getZodiosEndpointDefinitionList.ts
lib/tests/defaut-status-behavior.test.ts
lib/tests/samples.test.ts

https://github.com/astahmer/openapi-zod-client/issues/73

fix(#73): fallback response to void when no schemas

---

lib/src/getZodiosEndpointDefinitionList.test.ts
lib/src/getZodiosEndpointDefinitionList.ts

Hey, noticed that our openAPI spec wasn't working with this client due to us relying on fallback names for codegen.
This PR attempts to fix this issue by using the fallback name for the zod var name.

feat: support undefined schema refs

---

.changeset/curly-cats-work.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/tests/common-parameters.test.ts

https://github.com/astahmer/openapi-zod-client/issues/78

feat(#76): support common PathItemObject["parameters"]

---

.changeset/ten-bikes-teach.md
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/template-context.ts

This is an improvement proposal to allow setting a custom alias generation function using the config option `withAlias`.
I am not sure if this is the right approach though, what do you think @astahmer ?

proposal: allow setting a custom alias generation function

---

.changeset/honest-kids-dress.md
lib/src/openApiToZod.ts
lib/tests/validations.test.ts

fix: handle `exclusiveMinimum: false`

---

.changeset/gorgeous-ravens-act.md
.gitignore
lib/src/openApiToZod.ts
lib/src/utils.ts
lib/tests/validations.test.ts

fix: handle patterns with forward slashes 

---

.changeset/smart-files-heal.md
lib/src/openApiToZod.test.ts
lib/src/openApiToZod.ts
lib/tests/array-oneOf-discriminated-union.test.ts

fix(#116): rogue semicolon after `discriminatedUnion`

---

.changeset/tiny-mangos-invent.md
.github/workflows/ci.yml
.github/workflows/publish.yml
lib/package.json
lib/src/getZodiosEndpointDefinitionList.ts
pnpm-lock.yaml

also bumped ts-pattern and typescript to latest.

refactor: use more pattern matching

---

.changeset/rare-jokes-accept.md
lib/src/cli.ts
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/getZodiosEndpointDefinitionList.test.ts
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/template-context.ts
lib/tests/autofix-unusual-ref-format.test.ts
lib/tests/defaut-status-behavior.test.ts
lib/tests/export-schemas-option.test.ts
lib/tests/group-strategy.test.ts
lib/tests/handle-refs-with-dots-in-name.test.ts
lib/tests/handle-refs-without-var-name.test.ts
lib/tests/is-media-type-allowed.test.ts
lib/tests/missing-operationId-variables-undefined_Body.test.ts
lib/tests/name-starting-with-number.test.ts
lib/tests/name-with-special-characters.test.ts
lib/tests/recursive-schema.test.ts
lib/tests/ref-in-another-file.test.ts
lib/tests/same-schema-different-name.test.ts
lib/tests/schema-name-already-used.test.ts
lib/tests/with-deprecated.test.ts
playground/src/components/OptionsForm.tsx

fix: generate alias only when asked

---

lib/src/cli.ts
playground/package.json
playground/src/Playground/Playground.tsx
playground/src/components/OptionsForm.tsx
pnpm-lock.yaml

- fix #168 
- fix #169
- added `--no-with-alias` flag in order to not change behavior of [getRelevantOptions](https://github.com/astahmer/openapi-zod-client/blob/4f4e3c746e13da31b6006068794f1c33b86e2797/playground/src/Playground/Playground.tsx#L635-L647).
- made `--with-alias=false` to be interpreted as false (case insensitive)

fix: quirks with `withAlias` and `ts-pattern`

---

.changeset/happy-planes-float.md
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/getZodiosEndpointDefinitionList.test.ts
lib/src/openApiToZod.ts
lib/tests/validations.test.ts

Add nullable support for additional properties

---

.changeset/quick-jeans-hope.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/tests/resolve-ref-responses.test.ts

This quick fix should help with referenced responses (https://github.com/astahmer/openapi-zod-client/issues/178)

fix(#178): handle $ref in response object

---

.changeset/heavy-dancers-taste.md
lib/src/openApiToTypescript.test.ts
lib/src/openApiToTypescript.ts
lib/tests/export-all-types.test.ts

Fixes https://github.com/astahmer/openapi-zod-client/issues/208

Support nullable for array of types, oneOf, anyOf, and allOf in generated typescript types

---

README.md

Just a suggestion, since it's very convenient to have. 🙂

Add npmjs link in README

---

.changeset/feat/feat/add_additionalPropsDefaultValue_flag.md
lib/src/cli.ts
lib/src/openApiToZod.ts
lib/src/template-context.ts
lib/tests/additionalPropertiesDefaultValue-option.test.ts

Proposed solution for https://github.com/astahmer/openapi-zod-client/issues/196

Feat: Add additionalPropsDefaultValue flag

---

.changeset/honest-squids-hang.md
lib/package.json
pnpm-lock.yaml

Fixes https://github.com/astahmer/openapi-zod-client/issues/253

fix: Bump axios to avoid CVE-2023-45857

---

.changeset/two-pears-tap.md
lib/src/template-context.ts
lib/tests/array-body-with-chains-tag-group-strategy.test.ts

Fix array chaining bug with tag group strategy

---

.changeset/rude-ways-shake.md
lib/src/openApiToZod.ts
lib/tests/samples.test.ts

Added an explicit undefined check to prevent falsy values getting ignored

fix: falsy default values being ignored
