.github/workflows/ci.yml
.github/workflows/publish.yml

Hello alex,
I'm ready to help you. First thing, this PR is just to add github actions to automate your daily process :
- tests
- build
- publish
Note that publishing requires you to add a github secret named NPM_TOKEN else it wont work.
But it's really helpfull to automate this process.
You will gain a lot of time by doing this.
Automatic publish work by just adding a new tag.
so just doing : 
```bash
npm version <major|minor|patch>
git push --follow-tags
```
will create a new release automatically if the CI succeed.
Another thing, i propose to add (not this PR) is register a renovate bot. this will do all the maintainance for you. 
A lot of time gained from it.
But it as some consequences, like being spammed to update libs when new versions comes out.
So it's your choice

chore(gh-actions): initialize github actions

---

lib/src/openApiToZod.ts
lib/src/utils.ts
lib/tests/invalid-pattern-regex.test.ts

related to #49 
ref https://github.com/astahmer/openapi-zod-client/issues/49#issuecomment-1345370089
Targets characters are as follows:
- TAB, LF and CR
- `\t\n\r`
- C0 Control Codes except for TAB, LF, CR, and Space
- `\x00-\x08\x0B\x0C\x0E-\x1F\x7F`
- C1 Control Codes
- `\x80-\x9F`
- Non-character
- `\uFFFE\uFFFF`

fix(#49): escape control characters

---

lib/src/getZodiosEndpointDefinitionList.ts
lib/tests/schema-name-already-used.test.ts

During aliasing, some schemas are being substituted by the same safe name suffixed by `__2`, even if the suffixed formatted name is already present in context. 
This PR attempts to fix this issue by increasing the suffix integer and checking, whether the name is not present in context.

Fix schema name reuse with more than two occurrences

---

.changeset/four-parents-type.md
lib/src/openApiToZod.ts
lib/tests/array-default-values.test.ts

The "array" type got forgotten in `getZodChainableDefault`, resulting in a breaking output for any array with default values, [as reproduced here](https://openapi-zod-client.vercel.app/?doc=N4KABGBED2AOCmA7AhrAlpAXFAzAOgAZDIAacKNRAM2izFAgkgDd4AnAZzWkTsgEZCxMoygAXNGIA28PkgCuAWw5hFlVcgAekcgF8RUWMjEALDnQaNIAeg7JFsGRfKjIAc3hjno10bb3PdnNsAG0XHwhLCNdKPgBHeXYAT1Jw6KgURVlsSGQ2fySAWngHMRSDdKYOAGMTEuRvStcyhD48gtSmmLES4Po0rsgW7KgOMTZKNx0uxn0B9MgAE3gqZHkpL1CAXXmfXV2IOaaoyshYnITkzsHMkdz85CKxicQpitOausUG7BOmoaSrRy7Ue1xmZx6ykaMyYwz4z0m0xhRxhSxWaw2dDCMKsPFk73BYgA7rQDj4djN9k0Uek-tEzrwLok2OUyUxbm0HkVEEoAEbsMEfWr1aGDOHArmC-6SXqiwmAu48xT8thIykE07LVbrTZgbE4sD8DVNABMbMYFK6VMqNOidIiDPizNZ4I5EoKhWgvIAVvBql5jT5IJ8Rb9zbCFZyOoGHTKoWGDeJIzkvb7-VLBrA2HB2BJ4H17YMaLQE4mrOLRuNEeG9jXDjXbf8tRjdfqcYX-sW%2BLy8mrkTXLdSyY2fB2r …

Fix unhandled default values for "array" type

---

.changeset/chilled-rats-begin.md
lib/src/openApiToZod.test.ts
lib/src/openApiToZod.ts

`{ type: "number", enum: [2] }` results in `z.union([z.literal(2)])`, which is invalid as `z.union` requires at least two union members. 
The result should just be `z.literal(2)` instead.
[Reproduction here](https://openapi-zod-client.vercel.app/?doc=N4KABBYEQPYA4FMB2BDOBLKAuaBmAdAAxFQA04kU6SAZjNmKJM9AG4IBOAzujEg1ACMREuRaUALugkAbBAIDKAdxQBzVZzAAFBBK4SYHeWPHQZ6AMbIu8nE1PMoqALa3oAWQCSAFSgVxAL7%2BYAEmEFA2HOzcDADawcz2DuEArhwyAgAWEhJwWAD0%2BYh6Bkb4XCrqnPi8%2BayCfg5BzAC6YdBwKBKZXAxJLFBFur12CaZQGhJ9Y8nQXCnOzigcAJ4CADLo%2BmAoMjJgxb3ts%2BHwnF28SJ4AJgLm%2Bjp6ZDPJUBJqI2CxUIdQbS8OH7LFCuCScT7xE7JfpQwEuNxQczOaTPWEnKj8HBQACOKU4a2OaIG1wQXAsHHQcCkfAEAAkYEowEskCswNIEM4uGADGAjBI0kgdhIwHwENz0K4wAAKJYADzAgkIhAAlKiiYCjLj0EZbjgaLsbIT1eEyZkOShpsb0RIVogBNQwRoOGqrYC6BwllMsQ7cAAmRqu5jNV2hAEnYDQeECHhIGQaMDIBZkaDUAS4- …

fix: enum with a single member should not generate a zod union

---

.changeset/perfect-mirrors-bake.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/utils.ts
lib/tests/hyphenated-parameters.test.ts

When hyphenated path parameters are encountered, they are ignored in the generation step and kept as is eg. `param-Id`. When using the generated API, @zodios/code does not match these hyphenated parameters, but instead expect a camelCase parameter. 
This PR fixes this issue. 
@astahmer please let me know if this is rather something that should be addressed in the @zodios/code repo.

fix: correctly transform hyphenated path parameters

---

.changeset/wise-peas-lay.md
lib/src/openApiToTypescript.test.ts
lib/src/openApiToTypescript.ts

`user: { oneOf: [{ $ref: "#/components/schemas/User" }, { $ref: "#/components/schemas/Member" }] },` outputs `user: "User" | "Member" ` instead of `user: User | Member`.
The issue comes from the fact that `getTypescriptFromOpenApi` resolves a`$ref` name as a string literal, which is then passed to `t.union` (ie: `t.union(["User", "Member"])`).
It seems that the fix is to just resolve `$ref` as `t.reference(nameString)` instead of just `nameString`.
Added a test to repro the issue, here is how it failed before the fix:

Fix TS generation of [any|one|all]Of when used with refs

---

.changeset/thin-hats-sneeze.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/template-context.ts
lib/tests/refine-default-endpoint-callback.test.ts

This PR closes https://github.com/astahmer/openapi-zod-client/issues/173. Initially I wanted to pass it as another field of the parameter for `generateZodClientFromOpenAPI`, but seems like `TemplateContextOptions` is the better way. Let me know if it perhaps is better to move it to another part.
Bumping the minor version in the changeset since I consider it a new feature (?) CMIIW on this part.
The test part is using the example from the issue, that is, using the `security` and `operationId`, which doesn't exist in the default definition. After we add that refiner function, these 2 fields exist in the resulting endpoints definition.
```
➜ /workspaces/openapi-zod-client (gh-173-refiner-callback-fn) $ pnpm test
...
Test Files  54 passed (54)
Tests  95 passed (95)
Start at  14:40:44
Duration …
```

feat: add endpointDefinitionRefiner to TemplateContext options

---

lib/src/openApiToZod.ts
lib/tests/enum-min-max.test.ts

small fix: i noticed that `gte()`/`lte()` etc chains still got added to numerical enums. this wasn't caught by tests because the test case incorrectly used `min`/`max` instead of `minimum`/`maximum`.
now the generation will skip all chains for numerical enums and the test case has been updated

fix min/max handling for numerical enums

---

.changeset/fifty-vans-swim.md
lib/src/generateZodClientFromOpenAPI.test.ts
lib/src/template-context.ts
lib/tests/group-strategy.test.ts

This PR is a PoC to proof that when using `groupStrategy: "tag-file"`, the zod type of `Category` and `Tag` are generated last instead of first.
```diff
- const Category = z
-   .object({ id: z.number().int(), name: z.string() })
-   .partial()
-   .passthrough();
- const Tag = z
-   .object({ id: z.number().int(), name: z.string() })
-   .partial()
-   .passthrough();
const Pet = z
.object({
id: z.number().int().optional(),
name: z.string(),
--
tags: z.array(Tag).optional(),
status: z.enum(["available", "pending", "sold"]).optional(),
})
.passthrough();
+ const Category = z
+   .object({ id: z.number().int(), name: z.string() })
+   .partial()
+   .passthrough();
+ const Tag = z
+   .object({ id: z.number().int(), name: z.string() })
+   .partial()
+   .passthrough();
const ApiResponse = …
```

fix: fix order of schemas when using option groupStrategy: tag-file

---

.changeset/seven-hotels-raise.md
lib/src/template-context.ts
lib/tests/group-strategy.test.ts

Closes https://github.com/astahmer/openapi-zod-client/issues/186. Previously, in order for files to be moved to a common file, it needs to be imported/referenced at least 2 or more.
In this PR, it's reduced to at least 1. I have also updated one existing test for this effort, as well as creating one with example PetStore YAML -- basically making `Order` to depend on `Pet`. It resulted in `Pet`, `Category`, and `Tag` to be extracted to a common file, which is exactly the behavior proposed in the issue.
Let me know if you have concerns about this approach, thanks!

feat: reduce dependency count threshold for a type to be imported from common file to just 1

---

.changeset/support_camel_case_formatting_in_hbs.md
lib/src/getHandlebars.ts

Add `camelCase` formatting helper to `hbs` files.
Related issue:
https://github.com/astahmer/openapi-zod-client/issues/201

Add `camelCase` formatting helper to `hbs` files.

---

.changeset/blue-ways-change.md
lib/src/cli.ts
lib/src/template-context.ts
lib/tests/export-all-types.test.ts
playground/src/Playground/Playground.tsx

With the new --export-types flag, all schema are defined as TS types as well. The schema definition included a type assignment to the generated type. This is useful for schemas that are too large for TS to infer like deeply nested objects.
OpenApi supports `minimum`, `maximum`, `minLength`, `minItems`, etc. which are transpiled to the zod `.min()`, `.max()`, etc. methods on the schema.
These methods are not supported on `z.ZodType` types which causes a TS error when schemas are a non-object type and have these validation attributes on them.
This PR limits the OpenApi types for which non-circular types will be generated when `--export-types` is passed to only `object` types.
Additionally, the boolean lib option in the playground has been broken. This PR properly sets booleans in options …

Export only object types with --export-types flag, fix boolean options in playground

---

lib/src/openApiToTypescript.ts
lib/src/openApiToZod.ts
lib/tests/enum-null.test.ts

[OpenAPI 3.0.3 Data Types](https://spec.openapis.org/oas/v3.0.3#data-types) are defined by [JSON Schema Specification Wright Draft 00](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00#section-4.2).
However, the specification mentions that "null is not supported as a type" and the `nullable` keyword should be used instead. While it is a valid solution in most cases, it is not possible to use `nullable` together with `$ref`. One possible workaround is to define a Null schema and use it in combination with `oneOf`, like so:
```json
{
"oneOf": [
{ "$ref": "#/components/schemas/MySchema" },
{
"type": "string",
"enum": [null],
"nullable": true
}
]
}
```
It may look contradictory, but according to the [enum section of JSON Schema Validation Wright Draft …

Add support for null value in enums when using `--export-types`

---

.changeset/options-passed-when-shouldExportAllSchemas.md
lib/src/template-context.ts

Following latest update, I realized `options` are not passed to `getZodSchema` when `shouldExportAllSchemas` is true, resulting with `.passthrough()` on schemas even if `additionalPropertiesDefaultValue: false` is passed.
If this is too risky, I can only pass `additionalPropertiesDefaultValue` to options if needed.

fix: pass options when shouldExportAllSchemas is true

---

.changeset/little-shirts-fly.md
lib/src/getZodiosEndpointDefinitionList.ts

Closes https://github.com/astahmer/openapi-zod-client/issues/241. This PR updates the location where `endpointDefinitionRefiner` is going to be called.
Previously, it's called when the endpoint definition is still empty, but now it's placed where all fields have been filled accordingly.

chore: make endpointDefinitionRefiner to receive final fields that are going to be used in handlebars

---

.changeset/fix-additional-props-default-value-as-string.md
README.md
lib/src/cli.ts
lib/src/utils.ts
lib/tests/utils.test.ts

A feature (#230) was added to the `cli` to give a user flexibility of allowing additional properties on types defined by the generator by omitting the `.passthrough()` deceleration on a `zod` schema - which should resolve #196
When trying this feature, I discovered it wasn't possible to set the flag `additionalPropsDefaultValue` correctly as the cli returns a `string` and the `openApiToZod` method expects a `boolean` for this value
I've refactored the `match` statement used for `withAlias` to be a helper method called `toBoolean` and consumed from the same location as `withAlias` does.

fix: convert additionalPropsDefaultValue to bool

---

.changeset/fix-discriminated-union-issue.md
lib/src/openApiToZod.test.ts
lib/src/openApiToZod.ts

An issue was previously raised #110 whereby the `z.discriminatedUnion` caused issues in the gererated schema.
It appears the issue is caused by the `z.and` type, this breaks inference when used within a `z.discriminatedUnion`.
In order to solve this, whenever there are multiple objects defined within an `allOf` block we should instead opt to use a `z.union` type instead; which then allows the `z.and` type to be infered correctly.

fix: discriminatedUnion allOf issue

---

.changeset/selfish-pandas-repeat.md
lib/src/openApiToZod.ts
lib/tests/array-oneOf-discriminated-union.test.ts
lib/tests/infer-as-object-when-only-required-set.test.ts
lib/tests/required-additional-props-not-in-properties.test.ts

This is an attempt to fix #257 
Now `getZodSchema` would treat schema object with `required` defined as an array of type `object` and correctly infer the type.
The fix also checks extra properties in `required` array but not defined in `properties`, inferred as additional props.
The fix doesn't handle the case when `additionalProperties` are defined and mixed with `required` array. It seems that the current implementation doesn't handle the mix of `additionalProperties` and `properties` either. But it would be easy to append the `extraProperties` string generated from `required` to the code string generated for `additionalProperties`, after it's properly handled.

fix #257 to infer as object when only required array set

---

README.md
lib/src/cli.ts
lib/src/openApiToZod.ts
lib/src/template-context.ts
lib/tests/strictObjects-option.test.ts

Added an option to allow strict validation of objects (by adding `.strict()` to z.objects). This will make zod throw unknown key error whenever unexpected data is encountered.

Strict validation of objects

---

.changeset/blue-spies-nail.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/template-context.ts
lib/tests/export-all-named-schemas.test.ts

This PR provides a new option, `exportAllNamedSchemas`, to override that behavior and export all named schemas even if they are the same type. 
The default behavior was causing the same schema name to be used in multiple places and the semantics did not make sense. 
Example: 
This portion of schema with a complexity of 0 would result in a single `username: z.string()` schema set to both `username` and `password` query parameters, as well as any other parameters that are `schema.type: string`
```
/user/login:
get:
tags:
- user
summary: Logs user into the system
description: ""
operationId: loginUser
parameters:
- name: username
in: query
description: The user name for login
required: false
schema:
type: string
- name: password
in: query
description: The password for login in clear text …
```

feat: add exportAllNamedSchemas option to allow exporting duplicate schemas with different names.

---

.changeset/smooth-impalas-behave.md
lib/src/CodeMeta.ts
lib/src/getZodiosEndpointDefinitionList.test.ts
lib/src/getZodiosEndpointDefinitionList.ts
lib/tests/export-all-named-schemas.test.ts

After updating the package to 1.16.0 I realized it was only half a fix. When using the `exportAllNamedSchemas` option it did create new names for duplicate schemas, but then if it tried to use those names again it would end up using the last known name for the schema instead.

fix: bug with exportAllNamedSchemas

---

.changeset/chilly-needles-pump.md
lib/src/getZodiosEndpointDefinitionList.ts
lib/src/openApiToZod.ts
lib/tests/description-in-zod.test.ts

Properly handles multiline descriptions (currently, it's producing invalid code if it has more than 2 lines [because `replace` is used instead of `replaceAll`]. fixed to not ignore multiple lines at all)
Tests updated accordingly
Also kept the current behavior of using double quotes if the description hasn't multiple lines, to avoid updating lots of tests and unnecessary change in currently generated code

fix: multiline description

---

.changeset/ten-poems-appear.md
lib/src/openApiToZod.ts
lib/src/template-context.ts
lib/tests/schema-refiner.test.ts

This PR is an update for my previous PR (https://github.com/astahmer/openapi-zod-client/pull/282), adding a function to allow refining the schema sent to `getZodSchema`
I've also created a test with the use case of my previous PR
Please let me know if this meets your suggestion @astahmer

feat: schema refiner

---

.changeset/shy-rocks-fix.md
README.md
lib/src/cli.ts
lib/src/generateJSDocArray.ts
lib/src/openApiToTypescript.ts
lib/src/template-context.ts
lib/tests/jsdoc.test.ts

This pull request introduces a new feature to the `openapi-zod-client` tool, enabling the automatic generation of JSDoc comments for the generated types. This feature leverages the various OpenAPI schema options to provide rich documentation directly in the generated code.
With the `--with-docs` flag, the tool now generates JSDoc comments that include:
- Descriptions from the OpenAPI schema (`@description`).
- Examples (`@example`) and multiple examples for better illustration.
- Deprecation notices to indicate obsolete fields or types (`@deprecated`).
- Links to external documentation for further reading (`@see`).
- Format specifications for data validation (`@format`).
- Constraints such as `minimum` (`@minimum`), `maximum` (`@maximum`), `minLength` (`@minLength`), `maxLength` …

feat: Add JSDoc comments to generated types with `--with-docs` option
